--待办事项
DROP TABLE IF EXISTS `TASK`;
CREATE TABLE `TASK` (
  `TASK_ID` varchar(32) NOT NULL COMMENT '主键：任务ID',
  `USER_ID` varchar(32) NOT NULL COMMENT '外键：用户ID',
  `STATUS` varchar(10) NOT NULL DEFAULT '0' COMMENT '状态（0:已创建 1:已完成）',
  `CONTENT` varchar(512) NOT NULL COMMENT '内容',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `DEADLINE_TIME` datetime DEFAULT NULL COMMENT '截至时间',
  `FINISH_TIME` datetime DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY(TASK_ID)
  --FOREIGN KEY(USER_ID) REFERENCES `USER_AUTH`(USER_ID)
);

--待办事项子任务
DROP TABLE IF EXISTS `TASK_STEP`;
CREATE TABLE `TASK_STEP` (
  `TASK_STEP_ID` varchar(32) NOT NULL COMMENT '主键：子任务ID',
  `TASK_ID` varchar(32) NOT NULL COMMENT '外键：任务ID',
  `STATUS` varchar(10) NOT NULL DEFAULT '0' COMMENT '状态（0:已创建 1:已完成）',
  `CONTENT` varchar(512) NOT NULL COMMENT '内容',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `DEADLINE_TIME` datetime DEFAULT NULL COMMENT '截至时间',
  `FINISH_TIME` datetime DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY(TASK_STEP_ID),
  FOREIGN KEY(TASK_ID) REFERENCES `TASK`(TASK_ID)
);
