--操作记录
DROP TABLE IF EXISTS `OPERATION`;
CREATE TABLE `OPERATION` (
  `OPERATION_ID` varchar(32) NOT NULL COMMENT '主键：操作ID',
  `USER_ID` varchar(32) NOT NULL COMMENT ' 外键：用户ID ',
  `TYPE` varchar(32) NOT NULL DEFAULT 0 COMMENT '操作类型',
  `CONTENT` varchar(1014) NOT NULL COMMENT '操作内容',
  `OPERATE_TIME` datetime NOT NULL COMMENT '操作时间',
  PRIMARY KEY(OPERATION_ID)
  --FOREIGN KEY(USER_ID) REFERENCES `USER_AUTH`(USER_ID)
);
